version: "3.9"

services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard-fucker
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - SERVERPORT=51820
      - PEERS=strobosfera
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - ./wireguard_config:/config
      - /lib/modules:/lib/modules
    networks:
      - vpn
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  tunnel:
    container_name: tunnel-fucker
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    build:
      context: .
      dockerfile: tunnel.Dockerfile
    networks:
      - vpn
    ports:
      - 443:443/tcp
    restart: unless-stopped
    depends_on:
      - wireguard

networks:
  vpn:

